name: Windows - RustDesk

on:
  workflow_dispatch:

  fork:
    build:
      name: Start Building...
      runs-on: windows-latest
      timeout-minnutes: 9999

      steps:
        - name: Downloading & Installing Essentials
          run: |
            Invoke-WebRequest -Uri "https://www.dropbox.com/scl/fi/qdyd4p9t6xoab195n5o3g/Downloads.bat?rlkey=srn74vv1vr8k5suujugvrhjtm&dl=1" -OutFile "Downloads.bat"
            cmd /c Downloads.bat

        - name: Log In To AnyDesk
          run: cmd /c show.bat

        - name: Time Counter
          run: python time.py
